name: "Delta Kernel Tests"
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      SCALA_VERSION: 2.12.18
    steps:
      - uses: actions/checkout@v3
      - name: [Kernel] Install java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "8"
      - name: [Kernel] Run tests
        run: |
          python run-tests.py --group kernel --coverage
      - name: [Kernel] Run integration tests
        run: |
          cd kernel/examples && python run-kernel-examples.py --use-local
